//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.23 at 07:16:49 PM EDT 
//


package com.main.util.sax;

import java.util.ArrayList;
import java.util.List;


/**
 * 
 *                 Can have up to 30 entries in the Derivative Table. This is Table 2 on the printed form.
 *                 Can have any combination of Transactions and Holdings in any order.
 *             
 * 
 * <p>Java class for DERIVATIVE_TABLE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DERIVATIVE_TABLE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="30" minOccurs="0"&gt;
 *         &lt;element name="derivativeTransaction" type="{}DERIVATIVE_TRANSACTION"/&gt;
 *         &lt;element name="derivativeHolding" type="{}DERIVATIVE_HOLDING"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

public class DERIVATIVETABLE {

    protected List<Object> derivativeTransactionOrDerivativeHolding;

    /**
     * Gets the value of the derivativeTransactionOrDerivativeHolding property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the derivativeTransactionOrDerivativeHolding property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDerivativeTransactionOrDerivativeHolding().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DERIVATIVETRANSACTION }
     * {@link DERIVATIVEHOLDING }
     * 
     * 
     */
    public List<Object> getDerivativeTransactionOrDerivativeHolding() {
        if (derivativeTransactionOrDerivativeHolding == null) {
            derivativeTransactionOrDerivativeHolding = new ArrayList<Object>();
        }
        return this.derivativeTransactionOrDerivativeHolding;
    }

}
