//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.23 at 07:16:49 PM EDT 
//


package com.main.util.sax;




/**
 * <p>Java class for DERIVATIVE_HOLDING complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DERIVATIVE_HOLDING"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="securityTitle" type="{}SECURITY_TITLE"/&gt;
 *         &lt;element name="conversionOrExercisePrice" type="{}OPT_NUMBER_WITH_FOOTNOTE"/&gt;
 *         &lt;element name="exerciseDate" type="{}OPT_DATE_WITH_FOOTNOTE"/&gt;
 *         &lt;element name="expirationDate" type="{}OPT_DATE_WITH_FOOTNOTE"/&gt;
 *         &lt;element name="underlyingSecurity" type="{}UNDERLYING_SECURITY"/&gt;
 *         &lt;element name="postTransactionAmounts" type="{}POST_TRANSACTION_AMOUNTS"/&gt;
 *         &lt;element name="ownershipNature" type="{}OWNERSHIP_NATURE"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
public class DERIVATIVEHOLDING {

    protected SECURITYTITLE securityTitle;
    protected OPTNUMBERWITHFOOTNOTE conversionOrExercisePrice;
    protected OPTDATEWITHFOOTNOTE exerciseDate;
    protected OPTDATEWITHFOOTNOTE expirationDate;
    protected UNDERLYINGSECURITY underlyingSecurity;
    protected POSTTRANSACTIONAMOUNTS postTransactionAmounts;
    protected OWNERSHIPNATURE ownershipNature;

    /**
     * Gets the value of the securityTitle property.
     * 
     * @return
     *     possible object is
     *     {@link SECURITYTITLE }
     *     
     */
    public SECURITYTITLE getSecurityTitle() {
        return securityTitle;
    }

    /**
     * Sets the value of the securityTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link SECURITYTITLE }
     *     
     */
    public void setSecurityTitle(SECURITYTITLE value) {
        this.securityTitle = value;
    }

    /**
     * Gets the value of the conversionOrExercisePrice property.
     * 
     * @return
     *     possible object is
     *     {@link OPTNUMBERWITHFOOTNOTE }
     *     
     */
    public OPTNUMBERWITHFOOTNOTE getConversionOrExercisePrice() {
        return conversionOrExercisePrice;
    }

    /**
     * Sets the value of the conversionOrExercisePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link OPTNUMBERWITHFOOTNOTE }
     *     
     */
    public void setConversionOrExercisePrice(OPTNUMBERWITHFOOTNOTE value) {
        this.conversionOrExercisePrice = value;
    }

    /**
     * Gets the value of the exerciseDate property.
     * 
     * @return
     *     possible object is
     *     {@link OPTDATEWITHFOOTNOTE }
     *     
     */
    public OPTDATEWITHFOOTNOTE getExerciseDate() {
        return exerciseDate;
    }

    /**
     * Sets the value of the exerciseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link OPTDATEWITHFOOTNOTE }
     *     
     */
    public void setExerciseDate(OPTDATEWITHFOOTNOTE value) {
        this.exerciseDate = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link OPTDATEWITHFOOTNOTE }
     *     
     */
    public OPTDATEWITHFOOTNOTE getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link OPTDATEWITHFOOTNOTE }
     *     
     */
    public void setExpirationDate(OPTDATEWITHFOOTNOTE value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the underlyingSecurity property.
     * 
     * @return
     *     possible object is
     *     {@link UNDERLYINGSECURITY }
     *     
     */
    public UNDERLYINGSECURITY getUnderlyingSecurity() {
        return underlyingSecurity;
    }

    /**
     * Sets the value of the underlyingSecurity property.
     * 
     * @param value
     *     allowed object is
     *     {@link UNDERLYINGSECURITY }
     *     
     */
    public void setUnderlyingSecurity(UNDERLYINGSECURITY value) {
        this.underlyingSecurity = value;
    }

    /**
     * Gets the value of the postTransactionAmounts property.
     * 
     * @return
     *     possible object is
     *     {@link POSTTRANSACTIONAMOUNTS }
     *     
     */
    public POSTTRANSACTIONAMOUNTS getPostTransactionAmounts() {
        return postTransactionAmounts;
    }

    /**
     * Sets the value of the postTransactionAmounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link POSTTRANSACTIONAMOUNTS }
     *     
     */
    public void setPostTransactionAmounts(POSTTRANSACTIONAMOUNTS value) {
        this.postTransactionAmounts = value;
    }

    /**
     * Gets the value of the ownershipNature property.
     * 
     * @return
     *     possible object is
     *     {@link OWNERSHIPNATURE }
     *     
     */
    public OWNERSHIPNATURE getOwnershipNature() {
        return ownershipNature;
    }

    /**
     * Sets the value of the ownershipNature property.
     * 
     * @param value
     *     allowed object is
     *     {@link OWNERSHIPNATURE }
     *     
     */
    public void setOwnershipNature(OWNERSHIPNATURE value) {
        this.ownershipNature = value;
    }

}
