//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.23 at 07:16:49 PM EDT 
//


package com.main.util.sax;

import java.util.ArrayList;
import java.util.List;
import lombok.ToString;


/**
 * 
 *                 Can have up to 30 entries in the Non-Derivative Table. This is Table 1 on the printed form.
 *                 Can have any combination of Transactions and Holdings in any order.
 *             
 * 
 * <p>Java class for NONDERIVATIVE_TABLE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NONDERIVATIVE_TABLE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="30" minOccurs="0"&gt;
 *         &lt;element name="nonDerivativeTransaction" type="{}NONDERIVATIVE_TRANSACTION"/&gt;
 *         &lt;element name="nonDerivativeHolding" type="{}NONDERIVATIVE_HOLDING"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@ToString
public class NONDERIVATIVETABLE {

    protected List<Object> nonDerivativeTransactionOrNonDerivativeHolding;

    /**
     * Gets the value of the nonDerivativeTransactionOrNonDerivativeHolding property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the nonDerivativeTransactionOrNonDerivativeHolding property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNonDerivativeTransactionOrNonDerivativeHolding().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NONDERIVATIVETRANSACTION }
     * {@link NONDERIVATIVEHOLDING }
     * 
     * 
     */
    public List<Object> getNonDerivativeTransactionOrNonDerivativeHolding() {
        if (nonDerivativeTransactionOrNonDerivativeHolding == null) {
            nonDerivativeTransactionOrNonDerivativeHolding = new ArrayList<Object>();
        }
        return this.nonDerivativeTransactionOrNonDerivativeHolding;
    }

}
