//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.23 at 07:16:49 PM EDT 
//


package com.main.util.sax;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import lombok.ToString;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="schemaVersion" type="{}SCHEMA_VERSION" minOccurs="0"/&gt;
 *         &lt;element name="documentType" type="{}DOCUMENT_TYPE"/&gt;
 *         &lt;element name="periodOfReport" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="notSubjectToSection16" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="issuer" type="{}ISSUER"/&gt;
 *         &lt;element name="reportingOwner" type="{}REPORTING_OWNER" maxOccurs="10"/&gt;
 *         &lt;element name="aff10b5One" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="nonDerivativeTable" type="{}NONDERIVATIVE_TABLE" minOccurs="0"/&gt;
 *         &lt;element name="derivativeTable" type="{}DERIVATIVE_TABLE" minOccurs="0"/&gt;
 *         &lt;element name="footnotes" type="{}FOOTNOTE_GROUP" minOccurs="0"/&gt;
 *         &lt;element name="remarks" type="{}STRING_2000" minOccurs="0"/&gt;
 *         &lt;element name="ownerSignature" type="{}SIGNATURE" maxOccurs="10"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@ToString
public class OwnershipDocument {

    protected String schemaVersion;
    protected String documentType;
    protected XMLGregorianCalendar periodOfReport;
    protected Boolean notSubjectToSection16;
    protected ISSUER issuer;
    protected List<REPORTINGOWNER> reportingOwner;
    protected boolean aff10B5One;
    protected NONDERIVATIVETABLE nonDerivativeTable;
    protected DERIVATIVETABLE derivativeTable;
    protected FOOTNOTEGROUP footnotes;
    protected String remarks;
    protected List<SIGNATURE> ownerSignature;

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the periodOfReport property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodOfReport() {
        return periodOfReport;
    }

    /**
     * Sets the value of the periodOfReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodOfReport(XMLGregorianCalendar value) {
        this.periodOfReport = value;
    }

    /**
     * Gets the value of the notSubjectToSection16 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNotSubjectToSection16() {
        return notSubjectToSection16;
    }

    /**
     * Sets the value of the notSubjectToSection16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNotSubjectToSection16(Boolean value) {
        this.notSubjectToSection16 = value;
    }

    /**
     * Gets the value of the issuer property.
     * 
     * @return
     *     possible object is
     *     {@link ISSUER }
     *     
     */
    public ISSUER getIssuer() {
        return issuer;
    }

    /**
     * Sets the value of the issuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISSUER }
     *     
     */
    public void setIssuer(ISSUER value) {
        this.issuer = value;
    }

    /**
     * Gets the value of the reportingOwner property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the reportingOwner property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportingOwner().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link REPORTINGOWNER }
     * 
     * 
     */
    public List<REPORTINGOWNER> getReportingOwner() {
        if (reportingOwner == null) {
            reportingOwner = new ArrayList<REPORTINGOWNER>();
        }
        return this.reportingOwner;
    }

    /**
     * Gets the value of the aff10B5One property.
     * 
     */
    public boolean isAff10B5One() {
        return aff10B5One;
    }

    /**
     * Sets the value of the aff10B5One property.
     * 
     */
    public void setAff10B5One(boolean value) {
        this.aff10B5One = value;
    }

    /**
     * Gets the value of the nonDerivativeTable property.
     * 
     * @return
     *     possible object is
     *     {@link NONDERIVATIVETABLE }
     *     
     */
    public NONDERIVATIVETABLE getNonDerivativeTable() {
        return nonDerivativeTable;
    }

    /**
     * Sets the value of the nonDerivativeTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link NONDERIVATIVETABLE }
     *     
     */
    public void setNonDerivativeTable(NONDERIVATIVETABLE value) {
        this.nonDerivativeTable = value;
    }

    /**
     * Gets the value of the derivativeTable property.
     * 
     * @return
     *     possible object is
     *     {@link DERIVATIVETABLE }
     *     
     */
    public DERIVATIVETABLE getDerivativeTable() {
        return derivativeTable;
    }

    /**
     * Sets the value of the derivativeTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link DERIVATIVETABLE }
     *     
     */
    public void setDerivativeTable(DERIVATIVETABLE value) {
        this.derivativeTable = value;
    }

    /**
     * Gets the value of the footnotes property.
     * 
     * @return
     *     possible object is
     *     {@link FOOTNOTEGROUP }
     *     
     */
    public FOOTNOTEGROUP getFootnotes() {
        return footnotes;
    }

    /**
     * Sets the value of the footnotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link FOOTNOTEGROUP }
     *     
     */
    public void setFootnotes(FOOTNOTEGROUP value) {
        this.footnotes = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the ownerSignature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the ownerSignature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOwnerSignature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SIGNATURE }
     * 
     * 
     */
    public List<SIGNATURE> getOwnerSignature() {
        if (ownerSignature == null) {
            ownerSignature = new ArrayList<SIGNATURE>();
        }
        return this.ownerSignature;
    }

}
