//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.23 at 07:16:49 PM EDT 
//


package com.main.util.sax;



/**
 * 
 *                 If you set directOrIndirectOwnership to (I)ndirect, then
 *                 natureOfOwnership is actually mandatory.
 *             
 * 
 * <p>Java class for OWNERSHIP_NATURE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OWNERSHIP_NATURE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="directOrIndirectOwnership" type="{}OWNERSHIP_TYPE"/&gt;
 *         &lt;element name="natureOfOwnership" type="{}INDIRECT_NATURE" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
public class OWNERSHIPNATURE {

    protected OWNERSHIPTYPE directOrIndirectOwnership;
    protected INDIRECTNATURE natureOfOwnership;

    /**
     * Gets the value of the directOrIndirectOwnership property.
     * 
     * @return
     *     possible object is
     *     {@link OWNERSHIPTYPE }
     *     
     */
    public OWNERSHIPTYPE getDirectOrIndirectOwnership() {
        return directOrIndirectOwnership;
    }

    /**
     * Sets the value of the directOrIndirectOwnership property.
     * 
     * @param value
     *     allowed object is
     *     {@link OWNERSHIPTYPE }
     *     
     */
    public void setDirectOrIndirectOwnership(OWNERSHIPTYPE value) {
        this.directOrIndirectOwnership = value;
    }

    /**
     * Gets the value of the natureOfOwnership property.
     * 
     * @return
     *     possible object is
     *     {@link INDIRECTNATURE }
     *     
     */
    public INDIRECTNATURE getNatureOfOwnership() {
        return natureOfOwnership;
    }

    /**
     * Sets the value of the natureOfOwnership property.
     * 
     * @param value
     *     allowed object is
     *     {@link INDIRECTNATURE }
     *     
     */
    public void setNatureOfOwnership(INDIRECTNATURE value) {
        this.natureOfOwnership = value;
    }

}
