//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.23 at 07:16:49 PM EDT 
//


package com.main.util.sax;


import lombok.ToString;


/**
 * <p>Java class for POST_TRANSACTION_AMOUNTS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="POST_TRANSACTION_AMOUNTS"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="sharesOwnedFollowingTransaction" type="{}NUMBER_WITH_FOOTNOTE"/&gt;
 *         &lt;element name="valueOwnedFollowingTransaction" type="{}NUMBER_WITH_FOOTNOTE"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

@ToString
public class POSTTRANSACTIONAMOUNTS {

    protected NUMBERWITHFOOTNOTE sharesOwnedFollowingTransaction;
    protected NUMBERWITHFOOTNOTE valueOwnedFollowingTransaction;

    /**
     * Gets the value of the sharesOwnedFollowingTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link NUMBERWITHFOOTNOTE }
     *     
     */
    public NUMBERWITHFOOTNOTE getSharesOwnedFollowingTransaction() {
        return sharesOwnedFollowingTransaction;
    }

    /**
     * Sets the value of the sharesOwnedFollowingTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link NUMBERWITHFOOTNOTE }
     *     
     */
    public void setSharesOwnedFollowingTransaction(NUMBERWITHFOOTNOTE value) {
        this.sharesOwnedFollowingTransaction = value;
    }

    /**
     * Gets the value of the valueOwnedFollowingTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link NUMBERWITHFOOTNOTE }
     *     
     */
    public NUMBERWITHFOOTNOTE getValueOwnedFollowingTransaction() {
        return valueOwnedFollowingTransaction;
    }

    /**
     * Sets the value of the valueOwnedFollowingTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link NUMBERWITHFOOTNOTE }
     *     
     */
    public void setValueOwnedFollowingTransaction(NUMBERWITHFOOTNOTE value) {
        this.valueOwnedFollowingTransaction = value;
    }

}
