//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.23 at 07:16:49 PM EDT 
//


package com.main.util.sax;

import lombok.ToString;


/**
 * <p>Java class for REPORTING_OWNER complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REPORTING_OWNER"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="reportingOwnerId" type="{}REPORTING_ID"/&gt;
 *         &lt;element name="reportingOwnerAddress" type="{}REPORTING_ADDRESS" minOccurs="0"/&gt;
 *         &lt;element name="reportingOwnerRelationship" type="{}REPORTING_RELATIONSHIP"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

@ToString
public class REPORTINGOWNER {


    protected REPORTINGID reportingOwnerId;
    protected REPORTINGADDRESS reportingOwnerAddress;
    protected REPORTINGRELATIONSHIP reportingOwnerRelationship;

    /**
     * Gets the value of the reportingOwnerId property.
     * 
     * @return
     *     possible object is
     *     {@link REPORTINGID }
     *     
     */
    public REPORTINGID getReportingOwnerId() {
        return reportingOwnerId;
    }

    /**
     * Sets the value of the reportingOwnerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link REPORTINGID }
     *     
     */
    public void setReportingOwnerId(REPORTINGID value) {
        this.reportingOwnerId = value;
    }

    /**
     * Gets the value of the reportingOwnerAddress property.
     * 
     * @return
     *     possible object is
     *     {@link REPORTINGADDRESS }
     *     
     */
    public REPORTINGADDRESS getReportingOwnerAddress() {
        return reportingOwnerAddress;
    }

    /**
     * Sets the value of the reportingOwnerAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link REPORTINGADDRESS }
     *     
     */
    public void setReportingOwnerAddress(REPORTINGADDRESS value) {
        this.reportingOwnerAddress = value;
    }

    /**
     * Gets the value of the reportingOwnerRelationship property.
     * 
     * @return
     *     possible object is
     *     {@link REPORTINGRELATIONSHIP }
     *     
     */
    public REPORTINGRELATIONSHIP getReportingOwnerRelationship() {
        return reportingOwnerRelationship;
    }

    /**
     * Sets the value of the reportingOwnerRelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link REPORTINGRELATIONSHIP }
     *     
     */
    public void setReportingOwnerRelationship(REPORTINGRELATIONSHIP value) {
        this.reportingOwnerRelationship = value;
    }

}
