//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.23 at 07:16:49 PM EDT 
//


package com.main.util.sax;

import lombok.ToString;


/**
 * 
 *                 Each Reporting Owner must have at least one of the four relationship
 *                 booleans set to true. This is not enforced by this schema but will
 *                 be enforced during EDGAR processing.
 *             
 * 
 * <p>Java class for REPORTING_RELATIONSHIP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REPORTING_RELATIONSHIP"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isDirector" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="isOfficer" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="isTenPercentOwner" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="isOther" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="officerTitle" type="{}STRING_30" minOccurs="0"/&gt;
 *         &lt;element name="otherText" type="{}STRING_30" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

@ToString
public class REPORTINGRELATIONSHIP {

    protected Boolean isDirector;
    protected Boolean isOfficer;
    protected Boolean isTenPercentOwner;
    protected Boolean isOther;
    protected String officerTitle;
    protected String otherText;

    /**
     * Gets the value of the isDirector property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDirector() {
        return isDirector;
    }

    /**
     * Sets the value of the isDirector property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDirector(Boolean value) {
        this.isDirector = value;
    }

    /**
     * Gets the value of the isOfficer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsOfficer() {
        return isOfficer;
    }

    /**
     * Sets the value of the isOfficer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsOfficer(Boolean value) {
        this.isOfficer = value;
    }

    /**
     * Gets the value of the isTenPercentOwner property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsTenPercentOwner() {
        return isTenPercentOwner;
    }

    /**
     * Sets the value of the isTenPercentOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsTenPercentOwner(Boolean value) {
        this.isTenPercentOwner = value;
    }

    /**
     * Gets the value of the isOther property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsOther() {
        return isOther;
    }

    /**
     * Sets the value of the isOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsOther(Boolean value) {
        this.isOther = value;
    }

    /**
     * Gets the value of the officerTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficerTitle() {
        return officerTitle;
    }

    /**
     * Sets the value of the officerTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficerTitle(String value) {
        this.officerTitle = value;
    }

    /**
     * Gets the value of the otherText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherText() {
        return otherText;
    }

    /**
     * Sets the value of the otherText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherText(String value) {
        this.otherText = value;
    }

}
