//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.23 at 07:16:49 PM EDT 
//


package com.main.util.sax;

import lombok.ToString;


/**
 * <p>Java class for REPORTING_ID complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REPORTING_ID"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rptOwnerCik" type="{}CIK"/&gt;
 *         &lt;element name="rptOwnerCcc" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rptOwnerName" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="150"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

@ToString
public class REPORTINGID {


    protected String rptOwnerCik;
    protected String rptOwnerCcc;
    protected String rptOwnerName;

    /**
     * Gets the value of the rptOwnerCik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptOwnerCik() {
        return rptOwnerCik;
    }

    /**
     * Sets the value of the rptOwnerCik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptOwnerCik(String value) {
        this.rptOwnerCik = value;
    }

    /**
     * Gets the value of the rptOwnerCcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptOwnerCcc() {
        return rptOwnerCcc;
    }

    /**
     * Sets the value of the rptOwnerCcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptOwnerCcc(String value) {
        this.rptOwnerCcc = value;
    }

    /**
     * Gets the value of the rptOwnerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptOwnerName() {
        return rptOwnerName;
    }

    /**
     * Sets the value of the rptOwnerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptOwnerName(String value) {
        this.rptOwnerName = value;
    }

}
