//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.23 at 07:16:49 PM EDT 
//


package com.main.util.sax;



/**
 * 
 *                 A document submitted as part of a Reduced Content submission
 *                 can include an address for a Reporting Owner.
 *                 All address elements are optional.
 *                 
 *                 If you do not include any address element, EDGAR will retrieve
 *                 the Reporting Owner's address based upon the provided CIK.
 *                 This address will be included in the version of the document
 *                 that is disseminated.
 *             
 * 
 * <p>Java class for REPORTING_ADDRESS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REPORTING_ADDRESS"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rptOwnerStreet1" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="40"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rptOwnerStreet2" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="40"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rptOwnerCity" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="30"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rptOwnerState" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value=""/&gt;
 *               &lt;enumeration value=" "/&gt;
 *               &lt;enumeration value="  "/&gt;
 *               &lt;enumeration value="AL"/&gt;
 *               &lt;enumeration value="AK"/&gt;
 *               &lt;enumeration value="AZ"/&gt;
 *               &lt;enumeration value="AR"/&gt;
 *               &lt;enumeration value="CA"/&gt;
 *               &lt;enumeration value="CO"/&gt;
 *               &lt;enumeration value="CT"/&gt;
 *               &lt;enumeration value="DE"/&gt;
 *               &lt;enumeration value="DC"/&gt;
 *               &lt;enumeration value="FL"/&gt;
 *               &lt;enumeration value="GA"/&gt;
 *               &lt;enumeration value="HI"/&gt;
 *               &lt;enumeration value="ID"/&gt;
 *               &lt;enumeration value="IL"/&gt;
 *               &lt;enumeration value="IN"/&gt;
 *               &lt;enumeration value="IA"/&gt;
 *               &lt;enumeration value="KS"/&gt;
 *               &lt;enumeration value="KY"/&gt;
 *               &lt;enumeration value="LA"/&gt;
 *               &lt;enumeration value="ME"/&gt;
 *               &lt;enumeration value="MD"/&gt;
 *               &lt;enumeration value="MA"/&gt;
 *               &lt;enumeration value="MI"/&gt;
 *               &lt;enumeration value="MN"/&gt;
 *               &lt;enumeration value="MS"/&gt;
 *               &lt;enumeration value="MO"/&gt;
 *               &lt;enumeration value="MT"/&gt;
 *               &lt;enumeration value="NE"/&gt;
 *               &lt;enumeration value="NV"/&gt;
 *               &lt;enumeration value="NH"/&gt;
 *               &lt;enumeration value="NJ"/&gt;
 *               &lt;enumeration value="NM"/&gt;
 *               &lt;enumeration value="NY"/&gt;
 *               &lt;enumeration value="NC"/&gt;
 *               &lt;enumeration value="ND"/&gt;
 *               &lt;enumeration value="OH"/&gt;
 *               &lt;enumeration value="OK"/&gt;
 *               &lt;enumeration value="OR"/&gt;
 *               &lt;enumeration value="PA"/&gt;
 *               &lt;enumeration value="RI"/&gt;
 *               &lt;enumeration value="SC"/&gt;
 *               &lt;enumeration value="SD"/&gt;
 *               &lt;enumeration value="TN"/&gt;
 *               &lt;enumeration value="TX"/&gt;
 *               &lt;enumeration value="X1"/&gt;
 *               &lt;enumeration value="UT"/&gt;
 *               &lt;enumeration value="VT"/&gt;
 *               &lt;enumeration value="VA"/&gt;
 *               &lt;enumeration value="WA"/&gt;
 *               &lt;enumeration value="WV"/&gt;
 *               &lt;enumeration value="WI"/&gt;
 *               &lt;enumeration value="WY"/&gt;
 *               &lt;enumeration value="A0"/&gt;
 *               &lt;enumeration value="A1"/&gt;
 *               &lt;enumeration value="Z4"/&gt;
 *               &lt;enumeration value="A2"/&gt;
 *               &lt;enumeration value="A3"/&gt;
 *               &lt;enumeration value="A4"/&gt;
 *               &lt;enumeration value="A5"/&gt;
 *               &lt;enumeration value="A6"/&gt;
 *               &lt;enumeration value="A7"/&gt;
 *               &lt;enumeration value="A8"/&gt;
 *               &lt;enumeration value="A9"/&gt;
 *               &lt;enumeration value="B0"/&gt;
 *               &lt;enumeration value="B2"/&gt;
 *               &lt;enumeration value="Y6"/&gt;
 *               &lt;enumeration value="B3"/&gt;
 *               &lt;enumeration value="B4"/&gt;
 *               &lt;enumeration value="B5"/&gt;
 *               &lt;enumeration value="B6"/&gt;
 *               &lt;enumeration value="B7"/&gt;
 *               &lt;enumeration value="1A"/&gt;
 *               &lt;enumeration value="B8"/&gt;
 *               &lt;enumeration value="B9"/&gt;
 *               &lt;enumeration value="C1"/&gt;
 *               &lt;enumeration value="1B"/&gt;
 *               &lt;enumeration value="1C"/&gt;
 *               &lt;enumeration value="C3"/&gt;
 *               &lt;enumeration value="C4"/&gt;
 *               &lt;enumeration value="1D"/&gt;
 *               &lt;enumeration value="C5"/&gt;
 *               &lt;enumeration value="C6"/&gt;
 *               &lt;enumeration value="C7"/&gt;
 *               &lt;enumeration value="C8"/&gt;
 *               &lt;enumeration value="1F"/&gt;
 *               &lt;enumeration value="C9"/&gt;
 *               &lt;enumeration value="D1"/&gt;
 *               &lt;enumeration value="G6"/&gt;
 *               &lt;enumeration value="D0"/&gt;
 *               &lt;enumeration value="D2"/&gt;
 *               &lt;enumeration value="D3"/&gt;
 *               &lt;enumeration value="1E"/&gt;
 *               &lt;enumeration value="B1"/&gt;
 *               &lt;enumeration value="D4"/&gt;
 *               &lt;enumeration value="D5"/&gt;
 *               &lt;enumeration value="D6"/&gt;
 *               &lt;enumeration value="D9"/&gt;
 *               &lt;enumeration value="E0"/&gt;
 *               &lt;enumeration value="X2"/&gt;
 *               &lt;enumeration value="E2"/&gt;
 *               &lt;enumeration value="E3"/&gt;
 *               &lt;enumeration value="E4"/&gt;
 *               &lt;enumeration value="E8"/&gt;
 *               &lt;enumeration value="E9"/&gt;
 *               &lt;enumeration value="F0"/&gt;
 *               &lt;enumeration value="F2"/&gt;
 *               &lt;enumeration value="F3"/&gt;
 *               &lt;enumeration value="F4"/&gt;
 *               &lt;enumeration value="F6"/&gt;
 *               &lt;enumeration value="F7"/&gt;
 *               &lt;enumeration value="F8"/&gt;
 *               &lt;enumeration value="F9"/&gt;
 *               &lt;enumeration value="G0"/&gt;
 *               &lt;enumeration value="Y3"/&gt;
 *               &lt;enumeration value="G1"/&gt;
 *               &lt;enumeration value="G2"/&gt;
 *               &lt;enumeration value="L7"/&gt;
 *               &lt;enumeration value="1M"/&gt;
 *               &lt;enumeration value="G3"/&gt;
 *               &lt;enumeration value="G4"/&gt;
 *               &lt;enumeration value="2N"/&gt;
 *               &lt;enumeration value="G7"/&gt;
 *               &lt;enumeration value="1G"/&gt;
 *               &lt;enumeration value="G9"/&gt;
 *               &lt;enumeration value="G8"/&gt;
 *               &lt;enumeration value="H1"/&gt;
 *               &lt;enumeration value="H2"/&gt;
 *               &lt;enumeration value="H3"/&gt;
 *               &lt;enumeration value="H4"/&gt;
 *               &lt;enumeration value="1J"/&gt;
 *               &lt;enumeration value="1H"/&gt;
 *               &lt;enumeration value="H5"/&gt;
 *               &lt;enumeration value="H7"/&gt;
 *               &lt;enumeration value="H6"/&gt;
 *               &lt;enumeration value="H8"/&gt;
 *               &lt;enumeration value="H9"/&gt;
 *               &lt;enumeration value="I0"/&gt;
 *               &lt;enumeration value="I3"/&gt;
 *               &lt;enumeration value="I4"/&gt;
 *               &lt;enumeration value="2C"/&gt;
 *               &lt;enumeration value="I5"/&gt;
 *               &lt;enumeration value="I6"/&gt;
 *               &lt;enumeration value="2Q"/&gt;
 *               &lt;enumeration value="2M"/&gt;
 *               &lt;enumeration value="J0"/&gt;
 *               &lt;enumeration value="J1"/&gt;
 *               &lt;enumeration value="J3"/&gt;
 *               &lt;enumeration value="J4"/&gt;
 *               &lt;enumeration value="J5"/&gt;
 *               &lt;enumeration value="J6"/&gt;
 *               &lt;enumeration value="GU"/&gt;
 *               &lt;enumeration value="J8"/&gt;
 *               &lt;enumeration value="Y7"/&gt;
 *               &lt;enumeration value="J9"/&gt;
 *               &lt;enumeration value="S0"/&gt;
 *               &lt;enumeration value="K0"/&gt;
 *               &lt;enumeration value="K1"/&gt;
 *               &lt;enumeration value="K4"/&gt;
 *               &lt;enumeration value="X4"/&gt;
 *               &lt;enumeration value="K2"/&gt;
 *               &lt;enumeration value="K3"/&gt;
 *               &lt;enumeration value="K5"/&gt;
 *               &lt;enumeration value="K6"/&gt;
 *               &lt;enumeration value="Y8"/&gt;
 *               &lt;enumeration value="K7"/&gt;
 *               &lt;enumeration value="K8"/&gt;
 *               &lt;enumeration value="K9"/&gt;
 *               &lt;enumeration value="L0"/&gt;
 *               &lt;enumeration value="L2"/&gt;
 *               &lt;enumeration value="L3"/&gt;
 *               &lt;enumeration value="L6"/&gt;
 *               &lt;enumeration value="L8"/&gt;
 *               &lt;enumeration value="M0"/&gt;
 *               &lt;enumeration value="Y9"/&gt;
 *               &lt;enumeration value="M2"/&gt;
 *               &lt;enumeration value="1P"/&gt;
 *               &lt;enumeration value="M3"/&gt;
 *               &lt;enumeration value="J2"/&gt;
 *               &lt;enumeration value="M4"/&gt;
 *               &lt;enumeration value="M5"/&gt;
 *               &lt;enumeration value="M6"/&gt;
 *               &lt;enumeration value="1N"/&gt;
 *               &lt;enumeration value="M7"/&gt;
 *               &lt;enumeration value="1R"/&gt;
 *               &lt;enumeration value="M8"/&gt;
 *               &lt;enumeration value="M9"/&gt;
 *               &lt;enumeration value="N0"/&gt;
 *               &lt;enumeration value="N1"/&gt;
 *               &lt;enumeration value="N2"/&gt;
 *               &lt;enumeration value="1Q"/&gt;
 *               &lt;enumeration value="N4"/&gt;
 *               &lt;enumeration value="N5"/&gt;
 *               &lt;enumeration value="1U"/&gt;
 *               &lt;enumeration value="N6"/&gt;
 *               &lt;enumeration value="N7"/&gt;
 *               &lt;enumeration value="N8"/&gt;
 *               &lt;enumeration value="N9"/&gt;
 *               &lt;enumeration value="O0"/&gt;
 *               &lt;enumeration value="O1"/&gt;
 *               &lt;enumeration value="1T"/&gt;
 *               &lt;enumeration value="O2"/&gt;
 *               &lt;enumeration value="O3"/&gt;
 *               &lt;enumeration value="O4"/&gt;
 *               &lt;enumeration value="2P"/&gt;
 *               &lt;enumeration value="O5"/&gt;
 *               &lt;enumeration value="1K"/&gt;
 *               &lt;enumeration value="1S"/&gt;
 *               &lt;enumeration value="O9"/&gt;
 *               &lt;enumeration value="P0"/&gt;
 *               &lt;enumeration value="Z5"/&gt;
 *               &lt;enumeration value="P1"/&gt;
 *               &lt;enumeration value="P2"/&gt;
 *               &lt;enumeration value="P3"/&gt;
 *               &lt;enumeration value="E1"/&gt;
 *               &lt;enumeration value="T6"/&gt;
 *               &lt;enumeration value="P5"/&gt;
 *               &lt;enumeration value="P6"/&gt;
 *               &lt;enumeration value="P7"/&gt;
 *               &lt;enumeration value="P8"/&gt;
 *               &lt;enumeration value="1W"/&gt;
 *               &lt;enumeration value="Q2"/&gt;
 *               &lt;enumeration value="Q3"/&gt;
 *               &lt;enumeration value="Q4"/&gt;
 *               &lt;enumeration value="Q5"/&gt;
 *               &lt;enumeration value="Q6"/&gt;
 *               &lt;enumeration value="Q7"/&gt;
 *               &lt;enumeration value="1V"/&gt;
 *               &lt;enumeration value="Q8"/&gt;
 *               &lt;enumeration value="P4"/&gt;
 *               &lt;enumeration value="R0"/&gt;
 *               &lt;enumeration value="1Y"/&gt;
 *               &lt;enumeration value="1X"/&gt;
 *               &lt;enumeration value="R1"/&gt;
 *               &lt;enumeration value="R2"/&gt;
 *               &lt;enumeration value="R4"/&gt;
 *               &lt;enumeration value="R5"/&gt;
 *               &lt;enumeration value="R6"/&gt;
 *               &lt;enumeration value="R8"/&gt;
 *               &lt;enumeration value="R9"/&gt;
 *               &lt;enumeration value="S1"/&gt;
 *               &lt;enumeration value="PR"/&gt;
 *               &lt;enumeration value="S3"/&gt;
 *               &lt;enumeration value="S4"/&gt;
 *               &lt;enumeration value="S5"/&gt;
 *               &lt;enumeration value="1Z"/&gt;
 *               &lt;enumeration value="S6"/&gt;
 *               &lt;enumeration value="U8"/&gt;
 *               &lt;enumeration value="U7"/&gt;
 *               &lt;enumeration value="U9"/&gt;
 *               &lt;enumeration value="Z0"/&gt;
 *               &lt;enumeration value="Z1"/&gt;
 *               &lt;enumeration value="V0"/&gt;
 *               &lt;enumeration value="V1"/&gt;
 *               &lt;enumeration value="Y0"/&gt;
 *               &lt;enumeration value="S8"/&gt;
 *               &lt;enumeration value="S9"/&gt;
 *               &lt;enumeration value="T0"/&gt;
 *               &lt;enumeration value="T1"/&gt;
 *               &lt;enumeration value="Z2"/&gt;
 *               &lt;enumeration value="T2"/&gt;
 *               &lt;enumeration value="T8"/&gt;
 *               &lt;enumeration value="U0"/&gt;
 *               &lt;enumeration value="2B"/&gt;
 *               &lt;enumeration value="2A"/&gt;
 *               &lt;enumeration value="D7"/&gt;
 *               &lt;enumeration value="U1"/&gt;
 *               &lt;enumeration value="T3"/&gt;
 *               &lt;enumeration value="1L"/&gt;
 *               &lt;enumeration value="U3"/&gt;
 *               &lt;enumeration value="F1"/&gt;
 *               &lt;enumeration value="V2"/&gt;
 *               &lt;enumeration value="V3"/&gt;
 *               &lt;enumeration value="L9"/&gt;
 *               &lt;enumeration value="V6"/&gt;
 *               &lt;enumeration value="V7"/&gt;
 *               &lt;enumeration value="V8"/&gt;
 *               &lt;enumeration value="V9"/&gt;
 *               &lt;enumeration value="F5"/&gt;
 *               &lt;enumeration value="2D"/&gt;
 *               &lt;enumeration value="W0"/&gt;
 *               &lt;enumeration value="W1"/&gt;
 *               &lt;enumeration value="Z3"/&gt;
 *               &lt;enumeration value="W2"/&gt;
 *               &lt;enumeration value="W3"/&gt;
 *               &lt;enumeration value="W4"/&gt;
 *               &lt;enumeration value="W5"/&gt;
 *               &lt;enumeration value="W6"/&gt;
 *               &lt;enumeration value="W8"/&gt;
 *               &lt;enumeration value="2E"/&gt;
 *               &lt;enumeration value="W7"/&gt;
 *               &lt;enumeration value="2G"/&gt;
 *               &lt;enumeration value="W9"/&gt;
 *               &lt;enumeration value="2H"/&gt;
 *               &lt;enumeration value="C0"/&gt;
 *               &lt;enumeration value="X0"/&gt;
 *               &lt;enumeration value="2J"/&gt;
 *               &lt;enumeration value="X3"/&gt;
 *               &lt;enumeration value="2K"/&gt;
 *               &lt;enumeration value="2L"/&gt;
 *               &lt;enumeration value="X5"/&gt;
 *               &lt;enumeration value="Q1"/&gt;
 *               &lt;enumeration value="D8"/&gt;
 *               &lt;enumeration value="VI"/&gt;
 *               &lt;enumeration value="X8"/&gt;
 *               &lt;enumeration value="U5"/&gt;
 *               &lt;enumeration value="T7"/&gt;
 *               &lt;enumeration value="Y4"/&gt;
 *               &lt;enumeration value="Y5"/&gt;
 *               &lt;enumeration value="XX"/&gt;
 *               &lt;enumeration value="C2"/&gt;
 *               &lt;enumeration value="E5"/&gt;
 *               &lt;enumeration value="E7"/&gt;
 *               &lt;enumeration value="G5"/&gt;
 *               &lt;enumeration value="I7"/&gt;
 *               &lt;enumeration value="X9"/&gt;
 *               &lt;enumeration value="I8"/&gt;
 *               &lt;enumeration value="I9"/&gt;
 *               &lt;enumeration value="2F"/&gt;
 *               &lt;enumeration value="L1"/&gt;
 *               &lt;enumeration value="L4"/&gt;
 *               &lt;enumeration value="L5"/&gt;
 *               &lt;enumeration value="M1"/&gt;
 *               &lt;enumeration value="O6"/&gt;
 *               &lt;enumeration value="Q9"/&gt;
 *               &lt;enumeration value="R3"/&gt;
 *               &lt;enumeration value="T4"/&gt;
 *               &lt;enumeration value="U2"/&gt;
 *               &lt;enumeration value="U4"/&gt;
 *               &lt;enumeration value="U6"/&gt;
 *               &lt;enumeration value="X7"/&gt;
 *               &lt;enumeration value="Y2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rptOwnerZipCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="10"/&gt;
 *               &lt;pattern value="[0-9A-Za-z #-]*"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rptOwnerStateDescription" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rptOwnerGoodAddress" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

public class REPORTINGADDRESS {

    protected String rptOwnerStreet1;
    protected String rptOwnerStreet2;
    protected String rptOwnerCity;
    protected String rptOwnerState;
    protected String rptOwnerZipCode;
    protected String rptOwnerStateDescription;
    protected Boolean rptOwnerGoodAddress;

    /**
     * Gets the value of the rptOwnerStreet1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptOwnerStreet1() {
        return rptOwnerStreet1;
    }

    /**
     * Sets the value of the rptOwnerStreet1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptOwnerStreet1(String value) {
        this.rptOwnerStreet1 = value;
    }

    /**
     * Gets the value of the rptOwnerStreet2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptOwnerStreet2() {
        return rptOwnerStreet2;
    }

    /**
     * Sets the value of the rptOwnerStreet2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptOwnerStreet2(String value) {
        this.rptOwnerStreet2 = value;
    }

    /**
     * Gets the value of the rptOwnerCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptOwnerCity() {
        return rptOwnerCity;
    }

    /**
     * Sets the value of the rptOwnerCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptOwnerCity(String value) {
        this.rptOwnerCity = value;
    }

    /**
     * Gets the value of the rptOwnerState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptOwnerState() {
        return rptOwnerState;
    }

    /**
     * Sets the value of the rptOwnerState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptOwnerState(String value) {
        this.rptOwnerState = value;
    }

    /**
     * Gets the value of the rptOwnerZipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptOwnerZipCode() {
        return rptOwnerZipCode;
    }

    /**
     * Sets the value of the rptOwnerZipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptOwnerZipCode(String value) {
        this.rptOwnerZipCode = value;
    }

    /**
     * Gets the value of the rptOwnerStateDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptOwnerStateDescription() {
        return rptOwnerStateDescription;
    }

    /**
     * Sets the value of the rptOwnerStateDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptOwnerStateDescription(String value) {
        this.rptOwnerStateDescription = value;
    }

    /**
     * Gets the value of the rptOwnerGoodAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRptOwnerGoodAddress() {
        return rptOwnerGoodAddress;
    }

    /**
     * Sets the value of the rptOwnerGoodAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRptOwnerGoodAddress(Boolean value) {
        this.rptOwnerGoodAddress = value;
    }

}
