//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.23 at 07:16:49 PM EDT 
//


package com.main.util.sax;



/**
 * <p>Java class for UNDERLYING_SECURITY complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UNDERLYING_SECURITY"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="underlyingSecurityTitle" type="{}SECURITY_TITLE"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="underlyingSecurityShares" type="{}OPT_NUMBER_WITH_FOOTNOTE" minOccurs="0"/&gt;
 *           &lt;element name="underlyingSecurityValue" type="{}OPT_NUMBER_WITH_FOOTNOTE" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

public class UNDERLYINGSECURITY {

    protected SECURITYTITLE underlyingSecurityTitle;
    protected OPTNUMBERWITHFOOTNOTE underlyingSecurityShares;
    protected OPTNUMBERWITHFOOTNOTE underlyingSecurityValue;

    /**
     * Gets the value of the underlyingSecurityTitle property.
     * 
     * @return
     *     possible object is
     *     {@link SECURITYTITLE }
     *     
     */
    public SECURITYTITLE getUnderlyingSecurityTitle() {
        return underlyingSecurityTitle;
    }

    /**
     * Sets the value of the underlyingSecurityTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link SECURITYTITLE }
     *     
     */
    public void setUnderlyingSecurityTitle(SECURITYTITLE value) {
        this.underlyingSecurityTitle = value;
    }

    /**
     * Gets the value of the underlyingSecurityShares property.
     * 
     * @return
     *     possible object is
     *     {@link OPTNUMBERWITHFOOTNOTE }
     *     
     */
    public OPTNUMBERWITHFOOTNOTE getUnderlyingSecurityShares() {
        return underlyingSecurityShares;
    }

    /**
     * Sets the value of the underlyingSecurityShares property.
     * 
     * @param value
     *     allowed object is
     *     {@link OPTNUMBERWITHFOOTNOTE }
     *     
     */
    public void setUnderlyingSecurityShares(OPTNUMBERWITHFOOTNOTE value) {
        this.underlyingSecurityShares = value;
    }

    /**
     * Gets the value of the underlyingSecurityValue property.
     * 
     * @return
     *     possible object is
     *     {@link OPTNUMBERWITHFOOTNOTE }
     *     
     */
    public OPTNUMBERWITHFOOTNOTE getUnderlyingSecurityValue() {
        return underlyingSecurityValue;
    }

    /**
     * Sets the value of the underlyingSecurityValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link OPTNUMBERWITHFOOTNOTE }
     *     
     */
    public void setUnderlyingSecurityValue(OPTNUMBERWITHFOOTNOTE value) {
        this.underlyingSecurityValue = value;
    }

}
